variable "region_name" {}
variable "vpc_cidr_block" {}
variable "vpc_instance_tenancy" {}
variable "vpc_enable_dns_hostnames" {}
variable "vpc_enable_dns_support" {}
variable "vpc_name" {}
variable "pub1_subnet_cidr_block" {}
variable "pub1_sn_availability_zone" {}
# variable "map_public_ip_on_launch" {}
variable "vpc_pub1_sn_name" {}
variable "vpc_igw_name" {}
variable "rt_cidr_block" {}
variable "Pub1_routetable_name" {}
variable "Sg_name" {}
variable "ec2_ami_name" {}
variable "instance_type" {}
variable "ec2_key_name" {}
variable "ec2_associate_public_ip_address" {}
variable "ec2_availability_zone" {}
variable "ec2_name" {}
